SDA package with vector field
FlintHill/SUAS-Competition pull request #100
Opened 2018-01-05 18:03 UTC by liyu711

Deleted and added the original SDA package
Added the vector field method for moving obstacles only
Add new value to obstacle: type "moving" & "stationary"
New method get_force in VectorMath
New method about repulsive_force and attractive_force in obstacle_map

2018-01-06 16:22 UTC, DarkmatterVale requested changes

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackage/SDA/constants.py
> +    MOVING_OBSTACLE_SAFETY_RADIUS = 90
Please do not modify the SDA package contents.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackage/SDA/stationary_obstacle.py
> -from SDA import Obstacle
Do not modify SDAPackage contents.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackage/SDA/obstacle_map.py
> +    def is_moving_obstacle_in_path(self, obstacle):
Do not modify SDA package contents.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackage/SDA/mass.py
> +from SDA import *
Do not modify SDA package contents.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +from math import atan2, cos, sin, pi, sqrt
PEP8 requires only 1 import per line.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +from SDAWithVectorField import *
Please avoid ```*``` imports.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +	def __init__(self, drone_point, fly_zones):
Please add a blank line above the init method declaration.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +		self.attractive_force = numpy.array([0,0,0])
You do not need to declare the variables here; instead, you can just call the ```reset_attractive_force()``` and ```reset_repulsive_forces()``` methods here.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +	def add_force(self):
This method looks good, but we should change the name to be more descriptive to its function. How does ```update_repulsive_forces()``` sound?

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +	def set_attractive_force(self):
Again, we need a name change I think. What about ```update_attractive_force()```?

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +		attractive_force = self.attractive_force
Do you need to make these variables here or can you complete the calculation with the class variable?

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +        :type waypoint: Numpy Array
Fix spacing issue here.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/vector_math.py
> +
Remove these extra lines.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/vector_math.py
> +        return the force vector between two points
First word of the method comment should be capitalized.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/vector_math.py
> +        force_vector = np.array([1.0/pow(distance_vector[0],2),1.0/pow(distance_vector[1],2),1.0/pow(distance_vector[2],2)])
Please fix the spacing issues here.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/setup.py
> +    name = 'SDAWtihVectorField',
Please fix the typo with the name.

2018-01-06 16:22 UTC, DarkmatterVale commented on SDAPackageWithVectorField/setup.py
> +    author = 'Vale Tolpegin',
I am not the author of this package. You should use your name and email address.

2018-01-06 16:22 UTC, DarkmatterVale commented on tests/my_tests/test_obstacle_map_vectorfield.py
> +
Please remove extra lines here.

2018-01-06 16:22 UTC, DarkmatterVale commented on tests/unit_tests/test_obstacle_map.py
> +
Please remove extra lines here.

2018-01-06 16:22 UTC, DarkmatterVale commented on tests/unit_tests/test_sda_vector_math.py
> +from SDAWithVectorField import VectorMath
You should create a separate vector math test case for your package, and leave the other unit tests in operation.

2018-01-06 16:22 UTC, DarkmatterVale commented on tests/unit_tests/test_sda_vector_math.py
> +
Remove extra lines.

2018-01-07 21:35 UTC, DarkmatterVale requested changes
Getting much closer!

We need to fix the Travis tests as well as the comments.

2018-01-07 21:35 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/moving_obstacle.py
> -from SDA import Obstacle
Did you move this file from SDAPackage to the new SDA system?

2018-01-07 21:35 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/moving_obstacle.py
> +        self.type = "moving"
As we talked about in class, please you class type as the distinguisher between stationary and moving, not a string.

2018-01-07 21:35 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +from SDAWithVectorField import *
As we talked about in class, this is alright for the main file.

2018-01-07 21:35 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/obstacle_map.py
> +from math import atan2, cos, sin, pi, sqrt
This still needs to be addressed.

2018-01-07 21:35 UTC, DarkmatterVale commented on SDAPackageWithVectorField/SDAWithVectorField/stationary_obstacle.py
> +        return self.type
Same comment about the type issue.

2018-01-07 21:35 UTC, DarkmatterVale commented on install.sh
> +
Please remove the extra lines.

2018-01-07 21:35 UTC, DarkmatterVale commented on tests/unit_tests/test_obstacle_map.py
> +	def test_is_moving_obstacle_in_path(self):
We do not use the current SDA system for moving obstacles anymore. Please update your comment accordingly.

2018-01-07 21:39 UTC, DarkmatterVale commented
Also, just so everyone is on the same page, this PR will stay open until we are ready to merge the first version of this code in (when the simulator is completed and tested).

2018-02-06 04:20 UTC, jvillemare requested changes

2018-02-06 04:20 UTC, jvillemare commented on SDAPackageWithVectorField/SDAWithVectorField/Work need to be done
> +
This seems like a notes file. This shouldn't be committed, and instead kept somewhere in the Google Drive.

2018-02-06 04:20 UTC, jvillemare commented on SDAPackageWithVectorField/SDAWithVectorField/flight_boundaries_container.py
> +class FlightBoundariesContainer(object):
All classes should have block comments below the signature describing their purpose.

2018-02-06 04:20 UTC, jvillemare commented on SDAPackageWithVectorField/SDAWithVectorField/flight_boundary.py
> +    Provides an interface for flight zone boundaries
Class descriptions should are sentences, so they should have periods.

2018-02-06 04:20 UTC, jvillemare commented on SDAPackageWithVectorField/SDAWithVectorField/flight_boundaries_container.py
> +class FlightBoundariesContainer(object):
This applies to all other files in this PR, as multiple classes are missing block comments.

2018-03-06 21:26 UTC, closed without merging